name: Fetch and acknowledge contributors

on:
  push:
    branches:
      - test
      - main
jobs:
  fetch-acknowledge-contributors:
    uses: ingka-group-digital/ospo/.github/workflows/fetch-acknowledge-contributors.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}